# config.yml
# Database configuration
db_host: "10.10.30.121"
db_name: "ticketing_db"
db_user: "db_app_user"
db_pass: "ZdThM0(8&6"

# Secret key for encryption
encryption_key: "sk_live_es7CeLMShhd3YMtl2yz3q0om0p0hCYZW"

# Email configuration
smtp_server: "smtp.ictticketing.com"
smtp_port: 587
smtp_user: "admin@ictticketing.com
smtp_pass: "P@ssw0rd!2Â£"
escalation_email: "escalations@tkthelpdesk.com"